name: semgrep

on: push

jobs:
  semgrep:
    runs-on: ubuntu-20.04
    name: Scan
    steps:
      - uses: actions/checkout@v1
      - name: Semgrep
        id: semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/r2c-ci
